/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    JnAppHeader: typeof import('./components/JnAppHeader.vue')['default']
    JnDialog: typeof import('./components/JnDialog.vue')['default']
    JnDrawer: typeof import('./components/JnDrawer.vue')['default']
    JnPageLayout: typeof import('./components/JnPageLayout.vue')['default']
    UniBadge: typeof import('@/uni_modules/uni-badge/uni-badge.vue')['default']
    UniCalendar: typeof import('@/uni_modules/uni-calendar/uni-calendar.vue')['default']
    UniCard: typeof import('@/uni_modules/uni-card/uni-card.vue')['default']
    UniCollapse: typeof import('@/uni_modules/uni-collapse/uni-collapse.vue')['default']
    UniCollapseItem: typeof import('@/uni_modules/uni-collapse-item/uni-collapse-item.vue')['default']
    UniCombox: typeof import('@/uni_modules/uni-combox/uni-combox.vue')['default']
    UniCountdown: typeof import('@/uni_modules/uni-countdown/uni-countdown.vue')['default']
    UniDataCheckbox: typeof import('@/uni_modules/uni-data-checkbox/uni-data-checkbox.vue')['default']
    UniDataSelect: typeof import('@/uni_modules/uni-data-select/uni-data-select.vue')['default']
    UniDatetimePicker: typeof import('@/uni_modules/uni-datetime-picker/uni-datetime-picker.vue')['default']
    UniEasyinput: typeof import('@/uni_modules/uni-easyinput/uni-easyinput.vue')['default']
    UniFav: typeof import('@/uni_modules/uni-fav/uni-fav.vue')['default']
    UniGrid: typeof import('@/uni_modules/uni-grid/uni-grid.vue')['default']
    UniGridItem: typeof import('@/uni_modules/uni-grid-item/uni-grid-item.vue')['default']
    UniIcons: typeof import('@/uni_modules/uni-icons/uni-icons.vue')['default']
    UniLink: typeof import('@/uni_modules/uni-link/uni-link.vue')['default']
    UniList: typeof import('@/uni_modules/uni-list/uni-list.vue')['default']
    UniListItem: typeof import('@/uni_modules/uni-list-item/uni-list-item.vue')['default']
    UniLoadMore: typeof import('@/uni_modules/uni-load-more/uni-load-more.vue')['default']
    UniNoticeBar: typeof import('@/uni_modules/uni-notice-bar/uni-notice-bar.vue')['default']
    UniNumberBox: typeof import('@/uni_modules/uni-number-box/uni-number-box.vue')['default']
    UniPagination: typeof import('@/uni_modules/uni-pagination/uni-pagination.vue')['default']
    UniPopup: typeof import('@/uni_modules/uni-popup/uni-popup.vue')['default']
    UniRate: typeof import('@/uni_modules/uni-rate/uni-rate.vue')['default']
    UniSearchBar: typeof import('@/uni_modules/uni-search-bar/uni-search-bar.vue')['default']
    UniSection: typeof import('@/uni_modules/uni-section/uni-section.vue')['default']
    UniSegmentedControl: typeof import('@/uni_modules/uni-segmented-control/uni-segmented-control.vue')['default']
    UniSteps: typeof import('@/uni_modules/uni-steps/uni-steps.vue')['default']
    UniTable: typeof import('@/uni_modules/uni-table/uni-table.vue')['default']
    UniTag: typeof import('@/uni_modules/uni-tag/uni-tag.vue')['default']
    UniTd: typeof import('@/uni_modules/uni-td/uni-td.vue')['default']
    UniTh: typeof import('@/uni_modules/uni-th/uni-th.vue')['default']
    UniTitle: typeof import('@/uni_modules/uni-title/uni-title.vue')['default']
    UniTr: typeof import('@/uni_modules/uni-tr/uni-tr.vue')['default']
    UniTransition: typeof import('@/uni_modules/uni-transition/uni-transition.vue')['default']
  }
}
