INSERT OR IGNORE INTO base_options (
	id,
	option_type,
	option_code,
	option_name,
	sort_order,
	remark
) VALUES
	('opt-category-food', 'category', 'food', '食品', 10, '米面粮油、零食、饮料'),
	('opt-category-daily', 'category', 'daily_supply', '日用品', 20, '纸品、护理、消耗品'),
	('opt-category-medicine', 'category', 'medicine', '药品', 30, '常备药、保健用品'),
	('opt-category-cleaning', 'category', 'cleaning', '清洁用品', 40, '清洁剂、洗护用品'),
	('opt-category-other', 'category', 'other', '其他', 99, '未归类物品'),
	('opt-location-kitchen', 'location', 'kitchen', '厨房', 10, '常温食品和餐厨用品'),
	('opt-location-fridge', 'location', 'fridge', '冰箱冷藏', 20, '冷藏区'),
	('opt-location-freezer', 'location', 'freezer', '冰箱冷冻', 30, '冷冻区'),
	('opt-location-bathroom', 'location', 'bathroom', '卫生间', 40, '洗护与清洁用品'),
	('opt-location-cabinet', 'location', 'cabinet', '储物柜', 50, '杂物与备货'),
	('opt-location-bedroom', 'location', 'bedroom', '卧室', 60, '个人护理和常备品'),
	('opt-unit-piece', 'unit', 'piece', '件', 10, '单件物品'),
	('opt-unit-pack', 'unit', 'pack', '包', 20, '袋装或包装'),
	('opt-unit-bottle', 'unit', 'bottle', '瓶', 30, '瓶装'),
	('opt-unit-box', 'unit', 'box', '盒', 40, '盒装'),
	('opt-unit-bag', 'unit', 'bag', '袋', 50, '散装袋'),
	('opt-unit-kg', 'unit', 'kg', '公斤', 60, '重量单位'),
	('opt-unit-liter', 'unit', 'liter', '升', 70, '容量单位'),
	('opt-outbound-eat', 'outbound_reason', 'consume', '食用/使用', 10, '正常消耗'),
	('opt-outbound-discard', 'outbound_reason', 'discard', '丢弃', 20, '非过期丢弃'),
	('opt-outbound-expired', 'outbound_reason', 'expired_dispose', '过期报废', 30, '过期处理'),
	('opt-outbound-share', 'outbound_reason', 'share', '借出/分享', 40, '给家人或朋友');
